nginx:
  build: ./nginx
  ports:
    - "8080:80"
  volumes:
    - ./www.template:/etc/nginx/conf.d/default.conf
    - ./www:/usr/share/nginx/html
    - ./logs:/var/log/nginx    
    
  links:
    - php:php

php:
  build: ./php
  volumes:
    - ./www:/var/www/html