nginx:
  build: ./nginx
  ports:
    - "8080:80"
  volumes:
    - ./www.template:/etc/nginx/conf.d/default.conf
    - ./www:/usr/share/nginx/html
    - ./logs:/var/log/nginx    
  links:
    - php:php

php:
  build: ./php
  volumes:
    - ./www:/var/www/html
    - ./php/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
  command: /bin/bash -c "echo '* * * * * www-data /usr/local/bin/php /var/www/html/laravel/artisan schedule:run >> /dev/null 2>&1' >> /etc/crontab && /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf"